version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: payment-postgres
    environment:
      POSTGRES_DB: rideci_payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payments-network

  payments:
    build: .
    container_name: poseidon-payments
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rideci_payments
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Admin
      SERVER_PORT: 8081
    depends_on:
      - postgres
    networks:
      - payments-network

networks:
  payments-network:

volumes:
  postgres_data: